import Head from 'next/head'
import HomeInstitutional from '@/home/screens/institutional/institutional'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home institutional</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeInstitutional />
    </>
  )
}
